### ISSUE TITLE
Fix word-break in documentation

### ISSUE THREAD

**Issue by dylancaponi** [googleapis/python-pubsub#230]
Badly formatted sections of documentation where word-break causes the docs to be illegible. See screenshot examples below. Possibly expanding margins or turning off word-break for those elements could fix the problem.

#### Environment details

  - OS type and version: macOS Mojave 10.14.6 
  - Browser: Chrome Version 86.0.4240.111 _and_ Brave_ Version 1.16.68 Chromium
  - Resolution: 1080p
  - Python version: `python --version` n/a
  - pip version: `pip --version` n/a
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub` n/a

#### Steps to reproduce

  1. Go to: https://googleapis.dev/python/pubsub/latest/publisher/api/client.html?highlight=publish#google.cloud.pubsub_v1.publisher.client.Client.publish
  2. Search for `get_topic(` on page.

Normal:
![image](https://user-images.githubusercontent.com/7399067/97631407-26468a00-19ee-11eb-9e7e-c52f188b457b.png)

Turn word break off:
![image](https://user-images.githubusercontent.com/7399067/97631456-3fe7d180-19ee-11eb-87a0-cc3cdf8cbe42.png)

Better but still not quite right:
![image](https://user-images.githubusercontent.com/7399067/97631474-47a77600-19ee-11eb-9db7-9d98c5ea78a2.png)

Another example of difficult to read formatting:
![image](https://user-images.githubusercontent.com/7399067/97631693-935a1f80-19ee-11eb-990a-4077c72d4051.png)

#### Code example

In inspector you can turn on and off `word-break: break-word;` for `Return type:` and see how the formatting improves.

#### Stack trace

n/a

**Comment by plamut** [comment]
From what I can see, this has been (somewhat) addressed in the code generator, it sets the minimum width of the problematic column to 100px. Not a perfect fix, but it does improve readability significantly.

The changes will be included the next time we regenerate the generated parts of the library.

**Comment by dylancaponi** [comment]
@plamut Thanks! What triggers a regeneration? I am still experiencing this issue.

**Comment by plamut** [comment]
@dylancaponi The autogenerated part of the library is re-generated every now and then, either because of external changes such as new type definitions, or because the hand-written layer needs to make some adjustments.

I generated the docs locally and the rendering seems fine, thus I'd say the docs at `googleapis.dev/python/pubsub/latest/` have not been updated yet for some reason.

@anguillanneuf Do you have insight into the docs pipeline? What needs to be done to update them?
(I thought this is an automatic process every time a new client release is made)

**Comment by anguillanneuf** [comment]
It looks like your PR #297 picked up changes from synthtool https://github.com/googleapis/synthtool/pull/884, the published docs should reflect local changes with the next release.
